Web/Mastilo.Web/Controllers/CommentsController.cs
namespace Mastilo.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Mastilo.Data.Models;
    using Mastilo.Services.Data.Interfaces;
    using Mastilo.Web.Infrastructure.Mapping;
    using Mastilo.Web.ViewModels.CommentViewModels;
    using Microsoft.AspNet.Identity;

    [Authorize]
    public class CommentsController : BaseController
    {
        private readonly ICommentsService commentsService;

        public CommentsController(ICommentsService commentsService)
        {
            this.commentsService = commentsService;
        }

        public ActionResult AllById(int id = 1)
        {
            var comments = this.commentsService.AllById(id).To<CommentViewModel>().ToList();
            return this.PartialView("_CommentsSectionPartial", comments);
        }

        public ActionResult PostComment(CommentViewModel comment)
        {
            if (!this.ModelState.IsValid)
            {
                // TODO: Handle error
            }

            var commentDatabase = this.Mapper.Map<Comment>(comment);
            commentDatabase.UserId = this.User.Identity.GetUserId();
            this.commentsService.AddComment(commentDatabase);

            return this.RedirectToAction("AllById", new { id = comment.MasterpieceId });
        }

        public int VoteComment(int commentId)
        {
            var currentUserId = this.User.Identity.GetUserId();

            var count = this.commentsService.VoteComment(commentId, currentUserId);

            return count;
        }
    }
}

Web/Mastilo.Web/Controllers/ExploreController.cs
namespace Mastilo.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Infrastructure.Mapping;
    using Services.Data.Interfaces;
    using ViewModels.MasterpieceViewModels;

    public class ExploreController : BaseController
    {
        private readonly IMasterpiecesService masterpiecesService;
        private const int ItemsPerPage = 5;

        public ExploreController(IMasterpiecesService masterpiecesService)
        {
            this.masterpiecesService = masterpiecesService;
        }

        public ActionResult Index()
        {
            //var masterpieces = this.Cache.Get(
            //    "masterpieces",
            //    () => this.masterpiecesService.AllSortedByDate().To<MasterpieceResponseViewModel>().ToList(),
            //    10 * 60);

            var masterpieces = this.masterpiecesService.GetMasterpiecesByPageAndSort(string.Empty, "descending", string.Empty, 1, ItemsPerPage).To<MasterpieceResponseViewModel>().ToList();

            return this.View(new PagableMasterpieces() { Masterpieces = masterpieces, CurrentPage = 1, TotalPages = (int)Math.Ceiling(this.masterpiecesService.Count() / (decimal)ItemsPerPage) });
        }

        [HttpPost]
        public ActionResult Index(PagableMasterpieces model)
        {
            var page = model.CurrentPage;
            var sortType = model.SortField;
            var sortDirection = model.SortDirection;
            var searchValue = model.Search;

            var masterpieces = this.masterpiecesService.GetMasterpiecesByPageAndSort(sortType, sortDirection, searchValue, page, ItemsPerPage).To<MasterpieceResponseViewModel>().ToList();
            var postsNumber = 0;
            var totalPages = 0;

            if (model.Search == string.Empty || model.Search == null)
            {
                postsNumber = this.masterpiecesService.Count();
            }
            else
            {
                postsNumber = masterpieces.Count();
            }

            totalPages = (int)Math.Ceiling(postsNumber / (decimal)ItemsPerPage);

            model.TotalPages = totalPages;
            model.Masterpieces = masterpieces;

            var viewModel = model;

            return this.View(viewModel);
        }
    }
}

Web/Mastilo.Web/Controllers/MasterpieceController.cs
namespace Mastilo.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Data.Models;
    using Mastilo.Services.Data.Interfaces;
    using Mastilo.Web.Infrastructure.Mapping;
    using Mastilo.Web.ViewModels.GenreViewModels;
    using Mastilo.Web.ViewModels.MasterpieceViewModels;
    using Microsoft.AspNet.Identity;
    using ViewModels.CategoryViewModels;

    [Authorize]
    public class MasterpieceController : BaseController
    {
        private readonly int ItemsPerPage = 5;

        private readonly IGenresService genresService;
        private readonly IMasterpiecesService masterpiecesService;

        public MasterpieceController(IGenresService genresService, IMasterpiecesService masterpiecesService)
        {
            this.genresService = genresService;
            this.masterpiecesService = masterpiecesService;
        }

        public ActionResult Index(int page = 1, bool pending = false)
        {
            string userId = this.User.Identity.GetUserId();

            var masterpieces = new List<MasterpieceResponseViewModel>();

            if (pending)
            {
                masterpieces = this.masterpiecesService.AllByUserPending(userId).To<MasterpieceResponseViewModel>().ToList();
            }
            else
            {
                masterpieces = this.masterpiecesService.AllByUserApproved(userId).To<MasterpieceResponseViewModel>().ToList();
            }

            var postsNumber = this.masterpiecesService.Count();
            var totalPages = (int)Math.Ceiling(postsNumber / (decimal)this.ItemsPerPage);

            var viewModel = new PagableMasterpieces
            {
                CurrentPage = page,
                TotalPages = totalPages,
                Masterpieces = masterpieces
            };

            return this.View(viewModel);
        }

        [HttpGet]
        public ActionResult GetApprovedMasterpiecesByUser(string userId)
        {
            return this.RedirectToAction("Index", new { page = 1, pending = false });
        }

        [HttpGet]
        public ActionResult GetPendingMasterpiecesByUser(string userId)
        {
            return this.RedirectToAction("Index", new { page = 1, pending = true });
        }

        public ActionResult Create()
        {
            var genres = this.genresService.All().To<GenreViewModel>().ToList();

            var data = new MasterpieceRequestDataModel
            {
                Genres = genres,
                Masterpiece = new MasterpieceRequestViewModel()
            };

            return this.View(data);
        }

        [ValidateAntiForgeryToken]
        public ActionResult CreateMasterpiece(MasterpieceRequestDataModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("Create");
            }

            var masterpiece = model.Masterpiece;
            masterpiece.AuthorId = this.User.Identity.GetUserId();

            if (model.SelectedGroups != null)
            {
                foreach (var category in model.SelectedGroups)
                {
                    masterpiece.Categories.Add(new CategoriesViewModel { Name = category });
                }
            }

            this.masterpiecesService.Create(masterpiece.Title, masterpiece.Content, masterpiece.AuthorId, masterpiece.GenreId, this.Mapper.Map<ICollection<Category>>(masterpiece.Categories));
            this.TempData["SuccessCreateMasterpiece"] = "Your masterpiece was successfully created";

            return this.RedirectToAction("Index");
        }
    }
}

Web/Mastilo.Web/Views/Shared/_AddCommentPartial.cshtml
@model Mastilo.Web.ViewModels.CommentViewModels.CommentViewModel

@if (User.Identity.IsAuthenticated)
{
    using (Ajax.BeginForm("PostComment", "Comments", new { @class = "form-horizontal", role = "form" },
                                        new AjaxOptions
                                        {
                                            UpdateTargetId = "commentsSection",
                                            InsertionMode = InsertionMode.Replace
                                        }))
    {
        <h4>Коментирай:</h4>
        @Html.TextAreaFor(c => c.Text, new { style="width: 450px; height: 100px;" })
        @Html.HiddenFor(c => c.MasterpieceId, new { id = "masterpieceIdForAjax" })
        <br />
        <input class="btn btn-primary" type="submit" value="Добави!" />
    }
}
else
{
    <div class="well">
        <p>Регистрирай се за да коментираш!</p>
    </div>
}
<hr />
<div id="commentsSection"></div>

Web/Mastilo.Web/Views/Shared/_CommentPartial.cshtml
@model Mastilo.Web.ViewModels.CommentViewModels.CommentViewModel
<div style="background-color: rgba(245,245,245, 0.5)" class="well well-lg">
    <strong>@Model.AuthorName:</strong><br />
    <small>@Html.DisplayFor(c => c.CreatedOn)</small>
    <div class="row">
        <div class="col-md-6">
            <div class="well well-sm">
                <p>@Model.Text</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="pull-right">
                <button data-id="@Model.Id" data-action="up" class="glyphicon glyphicon-thumbs-up btn-lg"></button>
            </div>
            <div class="pull-right" data-id-count="@Model.Id" style="margin: 15px 30px; font-size: 22px;">
                <em>@Model.Likes.Count()</em>
            </div>
        </div>
    </div>
</div>

Web/Mastilo.Web/Views/Shared/_CommentsSectionPartial.cshtml
@model IEnumerable<Mastilo.Web.ViewModels.CommentViewModels.CommentViewModel>

@foreach (var comment in Model)
{
    Html.RenderPartial("_CommentPartial", comment);
}

Web/Mastilo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="http://bg.allfont.net/allfont.css?fonts=venski-sad-two-medium" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse  navbar-fixed-top">
        <div class="container">
            <div class="navbar-header navbar-left">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span>М а с т и л о</span>
                <img id="logoImage" src="~/Content/Images/ink-clipart-ink-splitter-md.png" />
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Актуални", "Index", "Explore", new { Area = "" }, null)</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Създай", "Create", "Masterpiece", new { Area = "" }, null)</li>
                    }
                    @if (User.IsInRole("Editor"))
                    {
                        <li>
                            @Html.ActionLink("≪ Контролен Панел", "New", "Approve", new { Area = "Editor" }, null)
                        </li>
                    }
                    else if (User.IsInRole("Administration"))
                    {
                        <li>
                            @Html.ActionLink("≪ Админ Панел", "Index", "Admin", new { Area = "Administration" }, null)
                        </li>
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div id="main-content">
            @RenderBody()
        </div>
        <hr />
        <footer>
            @RenderSection("UserInfo", required: false)
            <p>
                <img src="~/Content/Images/logo-white.png" />
                &copy; @DateTime.Now.Year - Сайт за лично творчество
            </p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/likeFunctionsBundle")
    @RenderSection("scripts", required: false)
    @RenderSection("Styles", required: false)
</body>
</html>

Web/Mastilo.Web/Views/Shared/_MasterpiecePartial.cshtml
@model MasterpieceResponseViewModel

<div class="row customBox">
    <a style="color: inherit;" href="PieceDetails/@Model.Id">
        <div style="font-size: 16px; text-decoration: underline; font-weight: bold;" class="col-xs-9">
            <span>@Model.Title</span>
        </div>
        <div class="col-xs-12">
            @if (Model.Content.Length < 120)
            {
                <span>@Html.Raw(Model.SanitizedContent)</span>
            }
            else
            {
                <span>@Html.Raw(Model.SanitizedContent.Substring(0, 120)) ...</span>
            }
        </div>
    </a>
</div>